# -*- coding: utf-8 -*-
"""First step - PostgreSQL and Airflow.ipynb
Automatically generated by Colaboratory.
"""

# Install Airflow
!pip install apache-airflow==2.1.4
!pip install wtforms==2.3.3
!pip install apache-airflow-providers-postgres

# DB initialization
!airflow db init

#Create directory and empty DAG file
!mkdir /root/airflow/dags
!touch /root/airflow/dags/dag.py

!airflow webserver -p 18273 -D

#Create new user with admin role
!airflow users create \
          --username admin \
          --firstname admin \
          --lastname admin \
          --role Admin \
          --email admin@example.org \
          -p 12345

#Run scheduler
!airflow scheduler -D

#map web interface to another endpoint
!pip install pyngrok
!ngrok authtoken <TOKEN> #https://dashboard.ngrok.com/get-started/setup 

# Link to the endpoints https://dashboard.ngrok.com/endpoints/status
!nohup ngrok http -log=stdout 18273 > /dev/null &

# Install postgresql server
!sudo apt-get -y -qq update
!sudo apt-get -y -qq install postgresql
!sudo service postgresql start

# Setup a password `postgres` for username `postgres`
!sudo -u postgres psql -U postgres -c "ALTER USER postgres PASSWORD 'postgres';"

# Setup a database with name `demo` to be used
!sudo -u postgres psql -U postgres -c 'DROP DATABASE IF EXISTS demo;'
!sudo -u postgres psql -U postgres -c 'CREATE DATABASE demo;'

!psql -d demo -U postgres -h localhost
